# -*- coding: utf-8 -*-


from detectron2.config import CfgNode as CN


def add_efficientnet_config(cfg):
    """
    Add config for efficientnets modeling
    """
    _C = cfg

    _C.MODEL.EFFICIENTNETS = CN()
    _C.MODEL.EFFICIENTNETS.NAME = "mixnet_m"
    _C.MODEL.EFFICIENTNETS.PRETRAINED = True
    _C.MODEL.EFFICIENTNETS.EXPORTABLE = False
    _C.MODEL.EFFICIENTNETS.SCRIPTABLE = False
    _C.MODEL.EFFICIENTNETS.OUT_FEATURES = []
    _C.MODEL.EFFICIENTNETS.NORM = "FrozenBN"
    cfg.MODEL.RPN.NORM = "SyncBN"


def add_roi_shared_config(cfg):
    """
    Add config for roi shared head
    """
    _C = cfg

    _C.MODEL.ROI_BOX_HEAD.IN_FEATURES = []

    _C.MODEL.ROI_SHARED_HEAD = CN()
    _C.MODEL.ROI_SHARED_HEAD.IN_FEATURES = ["p2"]
    _C.MODEL.ROI_SHARED_HEAD.POOLER_RESOLUTION = 32
    _C.MODEL.ROI_SHARED_HEAD.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.ROI_SHARED_HEAD.POOLER_SAMPLING_RATIO = 0

    _C.MODEL.ROI_SHARED_BLOCK = CN()
    _C.MODEL.ROI_SHARED_BLOCK.NAME = "ParsingSharedBlock"
    _C.MODEL.ROI_SHARED_BLOCK.ASPP_ON = True
    _C.MODEL.ROI_SHARED_BLOCK.ASPP_DIM = 256
    _C.MODEL.ROI_SHARED_BLOCK.ASPP_DILATION = (6, 12, 18)

    _C.MODEL.ROI_SHARED_BLOCK.NONLOCAL_ON = True
    _C.MODEL.ROI_SHARED_BLOCK.NONLOCAL_REDUCTION_RATIO = 0.5
    _C.MODEL.ROI_SHARED_BLOCK.NONLOCAL_USE_MAXPOOL = True
    _C.MODEL.ROI_SHARED_BLOCK.NONLOCAL_USE_BN = True

    _C.MODEL.ROI_SHARED_BLOCK.NUM_CONVS_BEFORE_ASPP_NL = 0
    _C.MODEL.ROI_SHARED_BLOCK.NUM_CONVS_AFTER_ASPP_NL = 4
    _C.MODEL.ROI_SHARED_BLOCK.CONV_HEAD_DIM = 512
    _C.MODEL.ROI_SHARED_BLOCK.CONV_HEAD_KERNEL = 3

    _C.MODEL.ROI_DENSEPOSE_PREDICTOR = CN()
    _C.MODEL.ROI_DENSEPOSE_PREDICTOR.NAME = "Default"
