_BASE_: "Base-DensePose-RCNN-FPN.yaml"
INPUT:
  FORMAT: "RGB"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_efficientnet_fpn_backbone"
    FREEZE_AT: 1
  EFFICIENTNETS:
    NAME: "mobilenetv3_rw"
    PRETRAINED: True
    OUT_FEATURES: ["s1","s2","s3","s5"]
    NORM: "SyncBN"
  FPN:
    IN_FEATURES: ["s1","s2","s3","s5"]
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)

